version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=mongodb
    depends_on:
      - mongodb

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb

  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    depends_on:
      - mongodb

  shipping-service:
    build: ./shipping-service
    ports:
      - "8084:8084"
    depends_on:
      - mongodb

  favourite-service:
    build: ./favourite-service
    ports:
      - "8085:8085"
    depends_on:
      - mongodb

  payment-service:
    build: ./payment-service
    ports:
      - "8086:8086"
    depends_on:
      - mongodb

volumes:
  mongo-data:
