version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - ecommerce-net

  user-service:
    image: ${DOCKERHUB_USERNAME}/user-service:stage
    ports:
      - "8081:8081"
    networks:
      - ecommerce-net

  product-service:
    image: ${DOCKERHUB_USERNAME}/product-service:stage
    ports:
      - "8082:8082"
    networks:
      - ecommerce-net

  order-service:
    image: ${DOCKERHUB_USERNAME}/order-service:stage
    ports:
      - "8083:8083"
    networks:
      - ecommerce-net

  shipping-service:
    image: ${DOCKERHUB_USERNAME}/shipping-service:stage
    ports:
      - "8084:8084"
    networks:
      - ecommerce-net

  favourite-service:
    image: ${DOCKERHUB_USERNAME}/favourite-service:stage
    ports:
      - "8085:8085"
    networks:
      - ecommerce-net

  payment-service:
    image: ${DOCKERHUB_USERNAME}/payment-service:stage
    ports:
      - "8086:8086"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
