pipeline {
    agent any

    environment {
        PROJECT_NAME = "product-service"
        IMAGE_NAME = "product-service:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build with Maven') {
            steps {
                dir("${PROJECT_NAME}") {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                dir("${PROJECT_NAME}") {
                    sh './mvnw test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}", "${PROJECT_NAME}")
                }
            }
        }
    }
}
