pipeline {
    agent {
        docker {
            image 'maven:3.8.5-openjdk-11'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        PROJECT_NAME = "product-service"
        JAR_NAME = "product-service-v0.1.0.jar"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build with Maven') {
            steps {
                dir("${PROJECT_NAME}") {
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                dir("${PROJECT_NAME}") {
                    sh './mvnw test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${PROJECT_NAME}:latest", "${PROJECT_NAME}")
                }
            }
        }
    }
}
