pipeline {
    agent any

    environment {
        PROJECT_NAME = "user-service"
        JAR_NAME = "user-service-v0.1.0.jar"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build with Maven') {
            steps {
                dir("${PROJECT_NAME}") {
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                dir("${PROJECT_NAME}") {
                    sh './mvnw test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${PROJECT_NAME}:latest ${PROJECT_NAME}"
                }
            }
        }
    }
}
